imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

security:
    encoders:
        MajorApi\AppBundle\Entity\Account: plaintext

web_profiler:
    toolbar: false
    intercept_redirects: false

doctrine:
    dbal:
        driver:   %test_database_driver%
        host:     %test_database_host%
        port:     %test_database_port%
        dbname:   %test_database_name%
        user:     %test_database_user%
        password: %test_database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true
