MajorApi\AppBundle\Entity\QuickbooksInvoice:
    type: entity
    table: api_quickbooks_invoice
    id:
        id:
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: api_quickbooks_invoice_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        created:
            column: created
            type: datetime
        updated:
            column: updated 
            type: datetime
        status:
            column: status
            type: integer
        applicationId:
            column: application_id
            type: integer
        quickbooksCustomerId:
            column: quickbooks_customer_id
            type: integer
        token:
            column: token
            type: string
            nullable: true
        invoiceDate:
            column: invoice_date
            type: datetime
        dueDate:
            column: due_date
            type: datetime
            nullable: true
        shipDate:
            column: ship_date
            type: datetime
            nullable: true
        refNumber:
            column: ref_number
            type: string
        poNumber:
            column: po_number
            type: string
            nullable: true
        isPending:
            column: is_pending
            type: boolean
        isFinanceCharge:
            column: is_finance_charge
            type: boolean
        isToBePrinted:
            column: is_to_be_printed
            type: boolean
        isToBeEmailed:
            column: is_to_be_emailed
            type: boolean
        billAddress1:
            column: bill_address1
            type: string
            nullable: true
        billAddress2:
            column: bill_address2
            type: string
            nullable: true
        billAddress3:
            column: bill_address3
            type: string
            nullable: true
        billAddress4:
            column: bill_address4
            type: string
            nullable: true
        billAddress5:
            column: bill_address5
            type: string
            nullable: true
        billCity:
            column: bill_city 
            type: string
            nullable: true
        billState:
            column: bill_state
            type: string
            nullable: true
        billPostalCode:
            column: bill_postal_code 
            type: string
            nullable: true
        billCountry:
            column: bill_country
            type: string
            nullable: true
        billNote:
            column: bill_note
            type: string
            nullable: true
        shipAddress1:
            column: ship_address1
            type: string
            nullable: true
        shipAddress2:
            column: ship_address2
            type: string
            nullable: true
        shipAddress3:
            column: ship_address3
            type: string
            nullable: true
        shipAddress4:
            column: ship_address4
            type: string
            nullable: true
        shipAddress5:
            column: ship_address5
            type: string
            nullable: true
        shipCity:
            column: ship_city 
            type: string
            nullable: true
        shipState:
            column: ship_state
            type: string
            nullable: true
        shipPostalCode:
            column: ship_postal_code 
            type: string
            nullable: true
        shipCountry:
            column: ship_country
            type: string
            nullable: true
        shipNote:
            column: ship_note
            type: string
            nullable: true
        fob:
            column: fob
            type: string
            nullable: true
        memo:
            column: memo
            type: string
            nullable: true
        importable:
            column: importable
            type: boolean
        quickbooksTxnId:
            column: quickbooks_txn_id
            type: string
            nullable: true
        quickbooksTxnNumber:
            column: quickbooks_txn_number
            type: string
            nullable: true
        quickbooksEditSequence:
            column: quickbooks_edit_sequence
            type: string
            nullable: true
    manyToOne:
        application:
            targetEntity: Application
            joinColumn:
                name: application_id
                referencedColumnName: id
        quickbooksCustomer:
            targetEntity: QuickbooksCustomer
            joinColumn:
                name: quickbooks_customer_id
                referencedColumnName: id
    oneToMany:
        quickbooksInvoiceLines:
            targetEntity: QuickbooksInvoiceLine
            mappedBy: quickbooksInvoice
            cascade: [ persist ]
    lifecycleCallbacks:
        prePersist: [ onCreate ]
        preUpdate: [ onUpdate ]
