MajorApi\AppBundle\Entity\RequestLog:
    type: entity
    table: api_request_log
    id:
        id:
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: api_request_log_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        created:
            column: created
            type: datetime
        updated:
            column: updated 
            type: datetime
        status:
            column: status
            type: integer
        applicationId:
            column: application_id
            type: integer
        requestMethod:
            column: request_method
            type: string
        responseCode:
            column: response_code
            type: integer
        route:
            column: route
            type: string
        startTime:
            column: start_time
            type: float
        endTime:
            column: end_time
            type: float
        requestTime:
            column: request_time
            type: float
        memoryUsage:
            column: memory_usage
            type: float
    manyToOne:
        application:
            targetEntity: Application
            joinColumn:
                name: application_id
                referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ onCreate ]
        preUpdate: [ onUpdate ]
